package com.conference.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EventContextAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventContextAllPropertiesEquals(EventContext expected, EventContext actual) {
        assertEventContextAutoGeneratedPropertiesEquals(expected, actual);
        assertEventContextAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventContextAllUpdatablePropertiesEquals(EventContext expected, EventContext actual) {
        assertEventContextUpdatableFieldsEquals(expected, actual);
        assertEventContextUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventContextAutoGeneratedPropertiesEquals(EventContext expected, EventContext actual) {
        assertThat(actual)
            .as("Verify EventContext auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventContextUpdatableFieldsEquals(EventContext expected, EventContext actual) {
        assertThat(actual)
            .as("Verify EventContext relevant properties")
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getEventContextStatus()).as("check eventContextStatus").isEqualTo(expected.getEventContextStatus())
            )
            .satisfies(a -> assertThat(a.getStart()).as("check start").isEqualTo(expected.getStart()))
            .satisfies(a -> assertThat(a.getEnd()).as("check end").isEqualTo(expected.getEnd()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventContextUpdatableRelationshipsEquals(EventContext expected, EventContext actual) {
        assertThat(actual)
            .as("Verify EventContext relationships")
            .satisfies(a -> assertThat(a.getEventContextRoom()).as("check eventContextRoom").isEqualTo(expected.getEventContextRoom()))
            .satisfies(a -> assertThat(a.getContextHost()).as("check contextHost").isEqualTo(expected.getContextHost()))
            .satisfies(a -> assertThat(a.getEvent()).as("check event").isEqualTo(expected.getEvent()));
    }
}
