package com.conference.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EventRegistrationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventRegistrationAllPropertiesEquals(EventRegistration expected, EventRegistration actual) {
        assertEventRegistrationAutoGeneratedPropertiesEquals(expected, actual);
        assertEventRegistrationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventRegistrationAllUpdatablePropertiesEquals(EventRegistration expected, EventRegistration actual) {
        assertEventRegistrationUpdatableFieldsEquals(expected, actual);
        assertEventRegistrationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventRegistrationAutoGeneratedPropertiesEquals(EventRegistration expected, EventRegistration actual) {
        assertThat(actual)
            .as("Verify EventRegistration auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventRegistrationUpdatableFieldsEquals(EventRegistration expected, EventRegistration actual) {
        assertThat(actual)
            .as("Verify EventRegistration relevant properties")
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getEventRegistrationStatus())
                    .as("check eventRegistrationStatus")
                    .isEqualTo(expected.getEventRegistrationStatus())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventRegistrationUpdatableRelationshipsEquals(EventRegistration expected, EventRegistration actual) {
        assertThat(actual)
            .as("Verify EventRegistration relationships")
            .satisfies(a -> assertThat(a.getEventCounterparty()).as("check eventCounterparty").isEqualTo(expected.getEventCounterparty()))
            .satisfies(a -> assertThat(a.getEventContext()).as("check eventContext").isEqualTo(expected.getEventContext()));
    }
}
